import { createFileRoute } from '@tanstack/react-router';
import { useState, type ReactNode } from 'react';
import { ArrowDown, ArrowRight, ArrowUp, ArrowUpRight, Award, BarChart3, BriefcaseBusiness, ChevronDown, Code2, Database, Linkedin, Mail, Palette } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Navigation, Wordmark } from '@/components/portfolio/navigation';
import { ProjectCard } from '@/components/portfolio/project-card';
import { Portrait } from '@/components/portfolio/portrait';
import { EvidenceGallery } from '@/components/portfolio/evidence';
import { CaseStudy } from '@/components/portfolio/case-study';
import { achievement, certificates, certificateCategories, education, experience, languages, leadership, profile, projectCategories, projects, skills, storyAssets, type Project } from '@/data/portfolio';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'Tarmuji Portfolio' },
    { name: 'description', content: 'Portfolio Tarmuji: perjalanan manufaktur Jepang, digital marketing, data analytics, karya kreatif, dan pengembangan teknologi berbasis bukti.' },
    { property: 'og:title', content: 'Tarmuji — Digital Business & Creative Professional' },
    { property: 'og:description', content: 'Dari data, ide, dan kreativitas menjadi pengalaman digital. Jelajahi proyek, pengalaman, sertifikasi, dan prestasi Tarmuji.' },
    { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
  ] }), component: Index,
});
function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: ReactNode; description?: string }) {
  return <div className="section-heading"><div><div className="eyebrow">{eyebrow}</div><h2 className="section-title">{title}</h2></div>{description && <p className="section-intro">{description}</p>}</div>;
}
const skillIcons = [BarChart3, Database, Palette, Code2, BriefcaseBusiness];
function Index() {
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [certificateFilter, setCertificateFilter] = useState('Semua');
  const [projectFilter, setProjectFilter] = useState('Semua');
  const filteredCertificates = certificates.filter(c => certificateFilter === 'Semua' || c.category === certificateFilter);
  const filteredProjects = projects.filter(p => projectFilter === 'Semua' || p.filter === projectFilter);
  return <><a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-50 focus:bg-card focus:p-3">Langsung ke konten</a><Navigation />
  <main id="main">
    <section id="home" className="hero-section"><div className="container-shell"><div className="hero-main">
      <div className="reveal"><div className="eyebrow">{profile.positioning}</div><h1 className="hero-name">Tarmuji<span className="gradient-text">.</span></h1>
        <h2 className="hero-title">Dari data, ide, dan kreativitas menjadi <span className="gradient-text">pengalaman digital.</span></h2>
        <p className="hero-copy">{profile.introduction}</p>
        <div className="hero-actions"><Button variant="portfolio" asChild><a href="#projects">Lihat Proyek <ArrowUpRight /></a></Button><Button variant="quiet" asChild><a href="#contact">Hubungi Saya <ArrowRight /></a></Button></div>
      </div>
      <Portrait />
    </div><div className="hero-bottom"><a href="#about" className="scroll-link"><ArrowDown size={13} /> KENALI PERJALANAN SAYA</a><span>BERANGKAT DARI PENGALAMAN. BERKARYA DENGAN TUJUAN.</span></div>
    <div className="stats-grid">{profile.stats.map(s => <div className="stat" key={s.value}><div className="stat-value">{s.value}</div><div className="stat-label">{s.label}</div><div className="stat-context">{s.context}</div></div>)}</div></div></section>
    <section id="about" className="section"><div className="container-shell"><div className="about-layout"><div><div className="eyebrow">01 / TENTANG SAYA</div><h2 className="section-title">Lintas disiplin.<br /><span className="gradient-text">Satu cara berpikir.</span></h2><div className="about-signature">Ketelitian bertemu kreativitas.</div></div><div className="about-copy"><p>Saya <strong>Tarmuji</strong>, seorang Digital Business & Creative Professional dengan perjalanan dari manufaktur menuju bisnis digital, pemasaran, data, karya kreatif, dan teknologi.</p><p>Pengalaman manufaktur di Indonesia dan <strong>Shiga, Jepang</strong> membentuk fondasi ketelitian, disiplin, kualitas, dan kerja sama. Melalui pendidikan Bisnis Digital, saya mengembangkan fondasi tersebut ke digital marketing, analisis data, dan produksi konten.</p><p>Kini, saya menghubungkan riset, ide, dan kreativitas dalam berbagai proyek: analisis sentimen, rancangan produk, konten digital, video, hingga pengembangan Roblox.</p></div></div><div className="journey" aria-label="Perjalanan profesional">{['MANUFAKTUR','JEPANG','BISNIS DIGITAL','DIGITAL MARKETING','DATA','CREATIVE','TECHNOLOGY'].map((step,i) => <span className="inline-flex items-center gap-3" key={step}>{i > 0 && <ArrowRight />}{step}</span>)}</div><EvidenceGallery title="Perjalanan pendidikan" assets={storyAssets.map(asset => { const src = profile.graduation || asset.src; return src ? { ...asset, src } : { alt: asset.alt, label: asset.label }; })} /></div></section>
    <section id="experience" className="section"><div className="container-shell"><SectionHeading eyebrow="02 / PENGALAMAN" title={<>Perjalanan yang dibentuk <span className="gradient-text">pengalaman nyata.</span></>} description="Dari ketelitian di lantai produksi hingga pengembangan karya dan strategi digital." />{experience.slice(0,4).map(e => <ExperienceRow key={e.company} item={e} />)}<details className="older-experience"><summary>Pengalaman sebelumnya · Manufaktur & Jepang <ChevronDown /></summary>{experience.slice(4).map(e => <ExperienceRow key={e.company} item={e} />)}</details></div></section>
    <section id="skills" className="section"><div className="container-shell"><SectionHeading eyebrow="03 / KEAHLIAN" title={<>Keahlian beragam. <span className="gradient-text">Pemikiran terhubung.</span></>} description="Bidang dan perangkat yang mendukung pekerjaan saya dalam strategi, analisis, kreativitas, dan pengembangan." /><div className="skill-grid">{skills.map((s,i) => { const Icon = skillIcons[i] ?? Code2; return <article className="skill-card" key={s.name}><Icon className="skill-icon" /><h3>{s.name}</h3><div className="skill-chips">{s.items.map(item => <span className="skill-chip" key={item}>{item}</span>)}</div></article>; })}</div></div></section>
    <section id="projects" className="section"><div className="container-shell"><SectionHeading eyebrow="04 / PROYEK PILIHAN" title={<>Dari pemikiran menjadi <span className="gradient-text">karya.</span></>} description="Karya akademik, profesional, dan pribadi, dengan peran dan batasan hasil yang jelas." /><div className="filter-row" aria-label="Filter proyek">{projectCategories.map(cat => <Button variant="filter" key={cat} aria-pressed={projectFilter === cat} onClick={() => setProjectFilter(cat)}>{cat}</Button>)}</div><p className="results-count" aria-live="polite">{filteredProjects.length} proyek · {projectFilter}</p><div className="project-grid">{filteredProjects.map(p => <ProjectCard key={p.id} project={p} onOpen={setSelectedProject} />)}</div></div></section>
    <section id="certificates" className="section"><div className="container-shell"><SectionHeading eyebrow="05 / SERTIFIKASI" title={<>Terus belajar. <span className="gradient-text">Terus berkembang.</span></>} description="Pilihan sertifikasi bahasa, data, pemasaran digital, dan kompetensi profesional yang relevan dengan pekerjaan saya." /><div className="filter-row" aria-label="Filter sertifikasi">{certificateCategories.map(cat => <Button variant="filter" key={cat} aria-pressed={certificateFilter === cat} onClick={() => setCertificateFilter(cat)}>{cat}</Button>)}</div><p className="results-count" aria-live="polite">{filteredCertificates.length} sertifikasi · {certificateFilter}</p><div className="certificate-grid">{filteredCertificates.map(c => <article key={c.id} className="certificate-card"><div className="certificate-preview">{c.image ? <img src={c.image} alt={`Sertifikat asli ${c.name}`} loading="lazy" /> : <><span className="certificate-kind">{c.category}</span><span className="certificate-year">{c.year}</span><span className="certificate-preview-note">Dokumen belum dipublikasikan</span></>}</div><div className="certificate-info"><h3>{c.name}</h3><p>{c.issuer ? `${c.issuer} · ` : ''}{c.year}<br />{c.category}</p></div></article>)}</div></div></section>
    <section id="achievements" className="section"><div className="container-shell"><div className="achievement" aria-labelledby="achievement-title"><div className="award-emblem"><Award /><span>GOLD<br />MEDAL</span></div><div><div className="eyebrow">06 / PRESTASI</div><h2 id="achievement-title">{achievement.title} <span className="gradient-text">— IITE 2024</span></h2><p>{achievement.event}</p><p>Kategori {achievement.category} · Produk {achievement.product}</p><p className="award-certificate">No. sertifikat: {achievement.certificate}</p></div><span className="award-year" aria-hidden="true">2024</span></div><SectionHeading eyebrow="KEPEMIMPINAN & ORGANISASI" title={<>Berkarya bersama. <span className="gradient-text">Memimpin dengan tujuan.</span></>} /><div className="leadership-grid">{leadership.map(([year,role,org]) => <article className="leadership-item" key={`${org}-${role}`}><span>{year}</span><div><h3>{role}</h3><p>{org}</p></div></article>)}</div></div></section>
    <section id="education" className="section"><div className="container-shell education-layout"><div><SectionHeading eyebrow="07 / PENDIDIKAN" title="Fondasi akademik." />{education.map(e => <article className="education-item" key={e.school}><h3>{e.degree}</h3><div className="education-meta"><span>{e.school}</span><span>{e.date}</span></div>{e.detail && <p>{e.detail}</p>}<p>{e.focus}</p>{e.school === 'Politeknik Takumi' && <a className="education-story-link" href="#about">Perjalanan pendidikan <ArrowUpRight size={16} /></a>}</article>)}</div><div><SectionHeading eyebrow="KOMUNIKASI LINTAS BUDAYA" title="Bahasa" />{languages.map(([name,level]) => <div className="language-row" key={name}><span>{name}</span><span>{level}</span></div>)}</div></div></section>
    <section id="contact" className="contact-section"><div className="container-shell"><div className="eyebrow">08 / HUBUNGI SAYA</div><h2 className="contact-title">PUNYA IDE?<br /><span className="gradient-text">MARI TERHUBUNG.</span></h2><p className="contact-subtext">Untuk percakapan tentang peluang kerja, kolaborasi, karya kreatif, dan tantangan bisnis digital.</p><Button variant="portfolio" asChild><a href={`mailto:${profile.contact.email}`} target="_blank" rel="noopener noreferrer">Kirim Email <ArrowUpRight /></a></Button><div className="contact-links"><a href={`mailto:${profile.contact.email}`} target="_blank" rel="noopener noreferrer"><Mail />{profile.contact.email}<ArrowUpRight size={12} /></a><a href={profile.contact.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin />LinkedIn<ArrowUpRight size={12} /></a></div></div></section>
  </main><footer className="container-shell footer"><a href="#home" aria-label="Beranda Tarmuji"><Wordmark /></a><p>© {profile.year} Tarmuji. Seluruh hak cipta dilindungi.</p><a href="#home" className="inline-flex items-center gap-2">Kembali ke atas <ArrowUp size={12} /></a></footer><CaseStudy project={selectedProject} onClose={() => setSelectedProject(null)} /></>;
}
function ExperienceRow({ item }: { item: typeof experience[number] }) { return <article className="experience-row"><span className="experience-date">{item.date}</span><div><h3>{item.role}</h3><p>{item.company}</p></div><span className="category-tag">{item.area}</span></article>; }
